import java_cup.runtime.*;

/* Terminales */ 

terminal             String        INT, DOUBLE, PYC, IDENT;


/* No Terminales */

non terminal                       lista, lista_enteros, lista_dobles;

lista         ::= INT    IDENT:id PYC                 {: System.out.println(id + ":int;");         :}
                | DOUBLE IDENT:id PYC                 {: System.out.println(id + ":double;");      :}
                | INT    IDENT:id lista_enteros:le    {: System.out.println(id + ":int; " + le);    :}
                | DOUBLE IDENT:id lista_dobles:ld     {: System.out.println(id + ":double; " + ld); :}
                ;

lista_enteros ::= IDENT:id lista_enteros:le   {: RESULT = id + ":int; " + le;  :}
                | IDENT:id PYC                {: RESULT = id + ":int;";       :}
                ;

lista_dobles  ::= IDENT:id lista_dobles:ld    {: RESULT = id + ":double; " + ld;  :}
                | IDENT:id PYC                {: RESULT = id + ":double;";       :}
                ;


